### ISSUE TITLE
I can't upload configuration files with ubxload utility

### ISSUE THREAD

**Issue by DavideLentini** [semuconsulting/pygnssutils#48] opened 2023-11-27 11:03 UTC
Hi all , I am trying to upload the configuration file (successfully saved with the ubxsave utility) to my F9P GPS , via the ubxload utility , but without success . 
The command I send is : 
`ubxload --port COM6 --baudrate 9600 --timeout 0.05 --infile lks.ubx --verbosity 1`
After about 1 minute of waiting , the utility returns me this error : 
`Something went wrong 'str' object has no attribute 'identity'` (ad infinitum) 
I then tried with the GUI , and it loads correctly . I do not know where I am going wrong . Thanks for any help .

**Comment by semuadmin** [comment] 2023-11-27 12:00
Hi @DavideLentini 

Sorry you're having difficulty.

I've just tried running `ubxsave` and `ubxload` using one of my own ZED-F9P devices and it does appear to be working OK:

```shell
➜  ~ ubxsave -P /dev/tty.usbmodem2101

Saving configuration from /dev/tty.usbmodem2101 to ubxconfig-20231127115043.ubx ...
Press Ctrl-C to terminate early.
Configuration successfully saved.                           
14 CFG-VALSET messages saved to ubxconfig-20231127115043.ubx

➜  ~ ubxload -P /dev/tty.usbmodem2101 -I ubxconfig-20231127115043.ubx

Loading configuration from ubxconfig-20231127115043.ubx to /dev/tty.usbmodem2101 ... 
Press Ctrl-C to terminate early.

Configuration successfully loaded. 
14 CFG-VALSET messages sent and acknowledged.
```

I can review the *.ubx file created using PyGPSClient (remembering to set the Msg Mode parameter to 'SET' first):

<img width="1352" alt="pygpsclient screenshot" src="https://github.com/semuconsulting/pygnssutils/assets/28569967/556950b8-86f8-46ca-aa21-a30020cec497">


Try running it without the `timeout` argument and see if that makes any difference. Failing that, could you send me a copy of the *.ubx file that `ubxsave` has generated?

**Comment by DavideLentini** [comment] 2023-11-27 15:11
@semuadmin 
Thanks , unfortunately I tried again without the timeout argument but the result is still the same , I share you attached the configuration file I am trying to use . The error traceback , is not very detailed , only the sentence I quoted initially appears to me . Thanks 
[ubxconfig-20231127160334.zip](https://github.com/semuconsulting/pygnssutils/files/13476791/ubxconfig-20231127160334.zip)

**Comment by semuadmin** [comment] 2023-11-27 15:44
Ok that's very odd. Your saved ubx loads fine into my F9P...

```shell
Loading configuration from ubxconfig-20231127160334.ubx to /dev/tty.usbmodem2101 ... 
Press Ctrl-C to terminate early.

Configuration successfully loaded. 
14 CFG-VALSET messages sent and acknowledged.
```

One thing I did notice, however, is that if I attempt to upload the same configuration twice, the device is unresponsive (the command just hangs). But if I power-cycle the device, it works fine again. Is there anything in your configuration that might be blocking UBX command inputs on the serial port?

**Comment by DavideLentini** [comment] 2023-11-28 09:28
Hello , here I am again . 
I tried resetting the F9P to factory settings , and indeed , the ubxload worked , I tried again a second time , and it did not work anymore , so I speculate that there is some setting in my configuration , which makes it difficult to do the operation

**Comment by DavideLentini** [comment] 2023-11-28 10:02
And also , is there a command for save the configuration in the ROM after load it with ubxload ?

**Comment by semuadmin** [comment] 2023-11-28 10:26
Hi @DavideLentini

Unfortunately I'm not able to recreate the exact error you were getting with your F9P.

I suspect the issue may simply be related to I/O bandwidth constraints on your device's UART port, though I'm still not clear why that would cause the specific error you've encountered. Have you tried using a faster baud rate? If you're intending to run at a high navigation solution rate, you might want to consider using a faster UART baud rate than 9600 - ideally 38,400 or higher (an F9P can comfortably go up to 230,400 if your client can handle it).

Re. your question around saving to ROM, the `ubxload` utility deliberately only saves to volatile RAM for safety reasons (to avoid any possibility of a user inadvertantly 'bricking' a device). You can use PyGPSClient's 'Save Configuration to Non-Volatile Memory' preset  - which utilises a UBX CFG-CFG command - to save to non-volatile memory.

**Comment by semuadmin** [comment] 2023-12-01 15:52
Closing for now as unable to reproduce - but happy to revisit.

**Comment by kodonnell** [comment] 2024-10-01 20:43
Just noting I'm having the exact same issue. I've got the F9R, and the only changes I made were (I think) upping rate to 10HZ and enabling UBX/suppressing NMEA, and setting the baudrate to 115200 . If I run ubxload once, all is fine. If I run it again, it hangs, and a restart is needed. I'm using 115200 baudrate ... and that sent me down the right path. On a fresh device, I'm guessing the device is set up to autobaud or something, and running `ubxload ...` works fine. But once I've run it once, it's now expecting 115200, and the same `ubxload ...` command fails. Changing it to `ubxload --baudrate 115200 ...` then works fine, and I can run it repeatedly.

My advice, to catch this sort of error, might be to add some basic check in UBXLoader that serial is working as expected - if not, there might be a baudrate issue, and you could warn the user of this. The current behaviour of hanging forever is also not really desirable, especially given the timeout argument. The trick here, I think, is specifying the `write_timeout` argument when you setup the `Serial` stream ... it's caught me out before, as you expect the `timeout` argument to be, well, a normal timeout = )

**Comment by semuadmin** [comment] 2024-10-01 21:42
> But once I've run it once, it's now expecting 115200, and the same `ubxload ...` command fails. Changing it to `ubxload --baudrate 115200 ...` then works fine, and I can run it repeatedly.

I may be misunderstanding the issue here but I would consider that normal and expected behaviour. If you apply a configuration which changes the baud rate on the port you're connected to, then you will need to use that new baud rate if you use ubxload again on the same port.

UBX devices don't 'autobaud' - if you don't use the correct baud rate for that port, the device will simply ignore you.

**Comment by kodonnell** [comment] 2024-10-01 22:22
> I may be misunderstanding the issue here but I would consider that normal and expected behaviour

Correct. It's just a gotcha, and detecting this and warning users might be nice. It caught me, and it possibly caught the OP, and it possibly caught you when you had the same issue running it multiple times. 

That said, it doesn't seem to be the complete fix for me, and things seems to hang after ubxload, even with (automated) device power cycling in between. (It wasn't write_timeout, it's timing out on read.) Oh well, I think I'll just assume it's persisted in non-volatile memory. If it's not, I'll create a manual script someone can run, that follows ubxload with a persist to non-volatile. Just looking for that command now in pygps now.

**Comment by semuadmin** [comment] 2024-10-01 22:30
As an aside, you can also use the gnssstreamer cli utility to apply a configuration from a binary file, e.g.

'''shell
gnssstreamer --port /dev/ttyACM0 --baudrate 38400 --cliinput 5 --input f9pconfig.ubx --verbosity 2
'''

... but you'll still get the same issue if you change the baud rate in an active UART port.

**Closed** 2024-10-11 07:48 UTC
Labels: bug
